# Generated by Django 4.0.5 on 2022-06-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
