# Generated by Django 4.0.5 on 2022-06-12 19:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='SpotsPost',
        ),
    ]
