# Generated by Django 4.0.5 on 2022-06-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_post_spotspost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotspost',
            old_name='author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='spotspost',
            old_name='body',
            new_name='Komentarz',
        ),
        migrations.RenameField(
            model_name='spotspost',
            old_name='title',
            new_name='Tytuł',
        ),
    ]
