# Generated by Django 4.0.5 on 2022-06-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_author_spotspost_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotspost',
            old_name='Autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='spotspost',
            old_name='Komentarz',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='spotspost',
            old_name='Tytuł',
            new_name='title',
        ),
    ]
