# Generated by Django 4.0.5 on 2022-06-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_spotscomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotscomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpotsComments', to='main.spotspost'),
        ),
    ]
