# Generated by Django 4.0.5 on 2022-06-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_spotscomment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotscomment',
            options={'verbose_name': 'Komentarz do miejscówek', 'verbose_name_plural': 'Komentarze do miejscówek'},
        ),
        migrations.AlterField(
            model_name='spotscomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotscomments', to='main.spotspost', verbose_name=''),
        ),
    ]
