# Generated by Django 4.0.5 on 2022-06-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_spotscomment_options_alter_spotscomment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotspost',
            options={'verbose_name': 'Miejscówka', 'verbose_name_plural': 'Miejscówki'},
        ),
    ]
